homepage: "https://github.com/Ga-Alves/cjson-fuzz"
language: c
primary_contact: "gabrielalvesreis@gmail.com"
main_repo: "https://github.com/Ga-Alves/cjson-fuzz"
file_github_issue: true
sanitizers:
- address
- undefined
- memory